spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_db?useSSL=false
    username: root
    password: oboxroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
  mail:
    host: mail.obox.com.ua
    port: 587
    username: support@obox.com.ua
    password: lzoEqcLT
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
server:
  error:
    include-stacktrace: never
    include-message: always
application:
  url: https://api.obox.com.ua
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days