spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 90000
      keepaliveTime: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: GMT+3
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  servlet:
    multipart:
      enabled: true # multipart support
      max-file-size: 10MB # max filesize
      max-request-size: 20MB # max all filesize
      file-size-threshold: 0 # threshold file size at which they will be written to temporary storage instead of permanent location
ftp:
  server: ${PROD_FTP_HOST}
  port: ${PROD_FTP_PORT}
  username: ${PROD_FTP_USER}
  password: ${PROD_FTP_PASSWORD}
server:
  error:
    include-stacktrace: never
    include-message: always
application:
  url: ${PROD_URL}
  image-dns: ${PROD_IMAGE_DNS}
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
bucket4j:
  get:
    capacity: ${GET_CAPACITY}
    regenerate: ${GET_REGENERATE}
  post:
    capacity: ${POST_CAPACITY}
    regenerate: ${POST_REGENERATE}
  patch:
    capacity: ${PATCH_CAPACITY}
    regenerate: ${PATCH_REGENERATE}
  delete:
    capacity: ${DELETE_CAPACITY}
    regenerate: ${DELETE_REGENERATE}
telegram:
  bot:
    name: ${BOT_NAME}
    token: ${BOT_TOKEN}